name: creators-OpsDev-CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-o: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm test

      - name: List workspace
        run: ls -la


      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: junit-report
          path: ./junit.xml

